### Initial imports

In [1]:
from sysinit.futures.seed_price_data_from_IB import seed_price_data_from_IB
from sysinit.futures.rollcalendars_from_db_prices_to_csv import (
    build_and_write_roll_calendar,
)
from sysinit.futures.multipleprices_from_db_prices_and_csv_calendars_to_db import (
    process_multiple_prices_single_instrument,
)
from sysinit.futures.adjustedprices_from_db_multiple_to_db import (
    process_adjusted_prices_single_instrument,
)
from ib_insync import util

util.startLoop()  # only required when running inside a notebook

Attempting to configure prod logging from /home/algotrader/pst/pysystemtrade/syslogging/logging_prod.yaml
Log server detected OK at localhost:9020

### Configuration
- define instrument
- define calendar output datapath

In [2]:
instrument_code = "EU-REALESTATE"
calendar_output_datapath = (
    "/home/algotrader/pst/pysystemtrade-private/private/futures/roll_calendars_csv/"
)

### Retrieve data from IB

In [3]:
seed_price_data_from_IB(instrument_code)

2026-01-14 12:17:01 DEBUG root {'component': 'mongoIbBrokerClientIdData'} Locked IB client ID 125
2026-01-14 12:17:06 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Getting data at frequency Frequency.Hour
2026-01-14 12:17:07 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Updating log attributes
2026-01-14 12:17:07 DEBUG root {'component': 'ibFuturesContractData'} Reqid -1: 2106 HMDS data farm connection is OK:euhmds for None
2026-01-14 12:17:07 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Reqid -1: 2106 HMDS data farm connection is OK:euhmds for None
2026-01-14 12:17:07 ERROR ib_insync.wrapper Error 162, reqId 471438: Historical Market Data Service error message:HMDS query returned no data: FSTL 20240315 M@EUREX Trades, contract: Contract(secType='FUT', conId=638120552, symbol='SX86P', lastTradeDateOrContractMonth='20240315', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240315 M', tradingClass='FSTL')
2026-01-14 12:17:07 DEBUG root {'component': 'ibFuturesContractData'} Reqid 471438: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240315 M@EUREX Trades for Contract(secType='FUT', conId=638120552, symbol='SX86P', lastTradeDateOrContractMonth='20240315', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240315 M', tradingClass='FSTL')
2026-01-14 12:17:07 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Reqid 471438: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240315 M@EUREX Trades for Contract(secType='FUT', conId=638120552, symbol='SX86P', lastTradeDateOrContractMonth='20240315', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240315 M', tradingClass='FSTL')
2026-01-14 12:17:07 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} No price data from IB
2026-01-14 12:17:07 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Something went wrong getting IB price data for EU-REALESTATE/20240300
2026-01-14 12:17:07 WARNING root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Error getting data for EU-REALESTATE/20240300
2026-01-14 12:17:07 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Getting data at frequency Frequency.Day
2026-01-14 12:17:07 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Updating log attributes
2026-01-14 12:17:07 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Pausing 0.485374 seconds to avoid pacing violation
2026-01-14 12:17:08 ERROR ib_insync.wrapper Error 162, reqId 471439: Historical Market Data Service error message:HMDS query returned no data: FSTL 20240315 M@EUREX Trades, contract: Contract(secType='FUT', conId=638120552, symbol='SX86P', lastTradeDateOrContractMonth='20240315', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240315 M', tradingClass='FSTL')
2026-01-14 12:17:08 DEBUG root {'component': 'ibFuturesContractData'} Reqid 471439: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240315 M@EUREX Trades for Contract(secType='FUT', conId=638120552, symbol='SX86P', lastTradeDateOrContractMonth='20240315', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240315 M', tradingClass='FSTL')
2026-01-14 12:17:08 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Reqid 471439: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240315 M@EUREX Trades for Contract(secType='FUT', conId=638120552, symbol='SX86P', lastTradeDateOrContractMonth='20240315', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240315 M', tradingClass='FSTL')
2026-01-14 12:17:08 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} No price data from IB
2026-01-14 12:17:08 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Something went wrong getting IB price data for EU-REALESTATE/20240300
2026-01-14 12:17:08 WARNING root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Error getting data for EU-REALESTATE/20240300
2026-01-14 12:17:08 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Writing merged data for EU-REALESTATE/20240300
2026-01-14 12:17:08 DEBUG root {'component': 'parquetFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240300'} Wrote 762 lines of prices for EU-REALESTATE/20240300 at Frequency.Mixed to parquetFuturesContractPriceData
2026-01-14 12:17:08 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Getting data at frequency Frequency.Hour
2026-01-14 12:17:08 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Updating log attributes
2026-01-14 12:17:08 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Pausing 0.347468 seconds to avoid pacing violation
2026-01-14 12:17:08 ERROR ib_insync.wrapper Error 162, reqId 471442: Historical Market Data Service error message:HMDS query returned no data: FSTL 20240621 M@EUREX Trades, contract: Contract(secType='FUT', conId=655096131, symbol='SX86P', lastTradeDateOrContractMonth='20240621', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240621 M', tradingClass='FSTL')
2026-01-14 12:17:08 DEBUG root {'component': 'ibFuturesContractData'} Reqid 471442: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240621 M@EUREX Trades for Contract(secType='FUT', conId=655096131, symbol='SX86P', lastTradeDateOrContractMonth='20240621', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240621 M', tradingClass='FSTL')
2026-01-14 12:17:08 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Reqid 471442: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240621 M@EUREX Trades for Contract(secType='FUT', conId=655096131, symbol='SX86P', lastTradeDateOrContractMonth='20240621', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240621 M', tradingClass='FSTL')
2026-01-14 12:17:08 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} No price data from IB
2026-01-14 12:17:08 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Something went wrong getting IB price data for EU-REALESTATE/20240600
2026-01-14 12:17:08 WARNING root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Error getting data for EU-REALESTATE/20240600
2026-01-14 12:17:08 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Getting data at frequency Frequency.Day
2026-01-14 12:17:08 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Updating log attributes
2026-01-14 12:17:08 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Pausing 0.482904 seconds to avoid pacing violation
2026-01-14 12:17:09 ERROR ib_insync.wrapper Error 162, reqId 471443: Historical Market Data Service error message:HMDS query returned no data: FSTL 20240621 M@EUREX Trades, contract: Contract(secType='FUT', conId=655096131, symbol='SX86P', lastTradeDateOrContractMonth='20240621', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240621 M', tradingClass='FSTL')
2026-01-14 12:17:09 DEBUG root {'component': 'ibFuturesContractData'} Reqid 471443: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240621 M@EUREX Trades for Contract(secType='FUT', conId=655096131, symbol='SX86P', lastTradeDateOrContractMonth='20240621', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240621 M', tradingClass='FSTL')
2026-01-14 12:17:09 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Reqid 471443: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240621 M@EUREX Trades for Contract(secType='FUT', conId=655096131, symbol='SX86P', lastTradeDateOrContractMonth='20240621', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240621 M', tradingClass='FSTL')
2026-01-14 12:17:09 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} No price data from IB
2026-01-14 12:17:09 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Something went wrong getting IB price data for EU-REALESTATE/20240600
2026-01-14 12:17:09 WARNING root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Error getting data for EU-REALESTATE/20240600
2026-01-14 12:17:09 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Writing merged data for EU-REALESTATE/20240600
2026-01-14 12:17:09 DEBUG root {'component': 'parquetFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240600'} Wrote 835 lines of prices for EU-REALESTATE/20240600 at Frequency.Mixed to parquetFuturesContractPriceData
2026-01-14 12:17:09 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Getting data at frequency Frequency.Hour
2026-01-14 12:17:09 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Updating log attributes
2026-01-14 12:17:09 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Pausing 0.376703 seconds to avoid pacing violation
2026-01-14 12:17:10 ERROR ib_insync.wrapper Error 162, reqId 471446: Historical Market Data Service error message:HMDS query returned no data: FSTL 20240920 M@EUREX Trades, contract: Contract(secType='FUT', conId=673277599, symbol='SX86P', lastTradeDateOrContractMonth='20240920', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240920 M', tradingClass='FSTL')
2026-01-14 12:17:10 DEBUG root {'component': 'ibFuturesContractData'} Reqid 471446: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240920 M@EUREX Trades for Contract(secType='FUT', conId=673277599, symbol='SX86P', lastTradeDateOrContractMonth='20240920', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240920 M', tradingClass='FSTL')
2026-01-14 12:17:10 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Reqid 471446: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240920 M@EUREX Trades for Contract(secType='FUT', conId=673277599, symbol='SX86P', lastTradeDateOrContractMonth='20240920', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240920 M', tradingClass='FSTL')
2026-01-14 12:17:10 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} No price data from IB
2026-01-14 12:17:10 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Something went wrong getting IB price data for EU-REALESTATE/20240900
2026-01-14 12:17:10 WARNING root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Error getting data for EU-REALESTATE/20240900
2026-01-14 12:17:10 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Getting data at frequency Frequency.Day
2026-01-14 12:17:10 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Updating log attributes
2026-01-14 12:17:10 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Pausing 0.484343 seconds to avoid pacing violation
2026-01-14 12:17:10 ERROR ib_insync.wrapper Error 162, reqId 471447: Historical Market Data Service error message:HMDS query returned no data: FSTL 20240920 M@EUREX Trades, contract: Contract(secType='FUT', conId=673277599, symbol='SX86P', lastTradeDateOrContractMonth='20240920', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240920 M', tradingClass='FSTL')
2026-01-14 12:17:10 DEBUG root {'component': 'ibFuturesContractData'} Reqid 471447: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240920 M@EUREX Trades for Contract(secType='FUT', conId=673277599, symbol='SX86P', lastTradeDateOrContractMonth='20240920', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240920 M', tradingClass='FSTL')
2026-01-14 12:17:10 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Reqid 471447: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20240920 M@EUREX Trades for Contract(secType='FUT', conId=673277599, symbol='SX86P', lastTradeDateOrContractMonth='20240920', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20240920 M', tradingClass='FSTL')
2026-01-14 12:17:10 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} No price data from IB
2026-01-14 12:17:10 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Something went wrong getting IB price data for EU-REALESTATE/20240900
2026-01-14 12:17:10 WARNING root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Error getting data for EU-REALESTATE/20240900
2026-01-14 12:17:10 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Writing merged data for EU-REALESTATE/20240900
2026-01-14 12:17:10 DEBUG root {'component': 'parquetFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20240900'} Wrote 819 lines of prices for EU-REALESTATE/20240900 at Frequency.Mixed to parquetFuturesContractPriceData
2026-01-14 12:17:10 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Getting data at frequency Frequency.Hour
2026-01-14 12:17:10 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Updating log attributes
2026-01-14 12:17:11 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Pausing 0.379999 seconds to avoid pacing violation
2026-01-14 12:17:11 ERROR ib_insync.wrapper Error 162, reqId 471450: Historical Market Data Service error message:HMDS query returned no data: FSTL 20241220 M@EUREX Trades, contract: Contract(secType='FUT', conId=691978342, symbol='SX86P', lastTradeDateOrContractMonth='20241220', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20241220 M', tradingClass='FSTL')
2026-01-14 12:17:11 DEBUG root {'component': 'ibFuturesContractData'} Reqid 471450: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20241220 M@EUREX Trades for Contract(secType='FUT', conId=691978342, symbol='SX86P', lastTradeDateOrContractMonth='20241220', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20241220 M', tradingClass='FSTL')
2026-01-14 12:17:11 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Reqid 471450: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20241220 M@EUREX Trades for Contract(secType='FUT', conId=691978342, symbol='SX86P', lastTradeDateOrContractMonth='20241220', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20241220 M', tradingClass='FSTL')
2026-01-14 12:17:11 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} No price data from IB
2026-01-14 12:17:11 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Something went wrong getting IB price data for EU-REALESTATE/20241200
2026-01-14 12:17:11 WARNING root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Error getting data for EU-REALESTATE/20241200
2026-01-14 12:17:11 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Getting data at frequency Frequency.Day
2026-01-14 12:17:11 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Updating log attributes
2026-01-14 12:17:11 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Pausing 0.482907 seconds to avoid pacing violation
2026-01-14 12:17:12 ERROR ib_insync.wrapper Error 162, reqId 471451: Historical Market Data Service error message:HMDS query returned no data: FSTL 20241220 M@EUREX Trades, contract: Contract(secType='FUT', conId=691978342, symbol='SX86P', lastTradeDateOrContractMonth='20241220', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20241220 M', tradingClass='FSTL')
2026-01-14 12:17:12 DEBUG root {'component': 'ibFuturesContractData'} Reqid 471451: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20241220 M@EUREX Trades for Contract(secType='FUT', conId=691978342, symbol='SX86P', lastTradeDateOrContractMonth='20241220', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20241220 M', tradingClass='FSTL')
2026-01-14 12:17:12 DEBUG root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Reqid 471451: 162 Historical Market Data Service error message:HMDS query returned no data: FSTL 20241220 M@EUREX Trades for Contract(secType='FUT', conId=691978342, symbol='SX86P', lastTradeDateOrContractMonth='20241220', multiplier='50', exchange='EUREX', currency='EUR', localSymbol='FSTL 20241220 M', tradingClass='FSTL')
2026-01-14 12:17:12 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} No price data from IB
2026-01-14 12:17:12 WARNING root {'component': 'ibFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Something went wrong getting IB price data for EU-REALESTATE/20241200
2026-01-14 12:17:12 WARNING root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Error getting data for EU-REALESTATE/20241200
2026-01-14 12:17:12 DEBUG root {'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Writing merged data for EU-REALESTATE/20241200
2026-01-14 12:17:12 DEBUG root {'component': 'parquetFuturesContractPriceData', 'instrument_code': 'EU-REALESTATE', 'contract_date': '20241200'} Wrote 818 lines of prices for EU-REALESTATE/20241200 at Frequency.Mixed to parquetFuturesContractPriceData

### Build roll calendar

This will build the calendar from the just retrieved prices. Make sure you have correctly set the output datapath in the above section.
After the calendar is generated, merge it with the production calendar. Default is in `~/pysystemtrade/private/futures/roll_calendars_csv`

In [4]:
build_and_write_roll_calendar(instrument_code, output_datapath=calendar_output_datapath)

Writing to /home/algotrader/pst/pysystemtrade-private/private/futures/roll_calendars_csv/
Prepping roll calendar... might take a few seconds
2015-06-11 00:00:00,20150600,20150900,20150900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff613f7200>
2015-09-11 00:00:00,20150900,20151200,20151200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6013d3d0>
2015-12-11 00:00:00,20151200,20160300,20160300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff58288470>
2016-03-11 00:00:00,20160300,20160600,20160600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff5828ab40>
2016-06-11 00:00:00,20160600,20160900,20160900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010e360>
2016-09-11 00:00:00,20160900,20161200,20161200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff60136480>
2016-12-11 00:00:00,20161200,20170300,20170300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff58288470>
2017-03-11 00:00:00,20170300,20170600,20170600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fce0>
2017-06-11 00:00:00,20170600,20170900,20170900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd10>
2017-09-11 00:00:00,20170900,20171200,20171200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010f830>
2017-12-11 00:00:00,20171200,20180300,20180300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd70>
2018-03-11 00:00:00,20180300,20180600,20180600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd10>
2018-06-11 00:00:00,20180600,20180900,20180900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010e360>
2018-09-11 00:00:00,20180900,20181200,20181200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd70>
2018-12-11 00:00:00,20181200,20190300,20190300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010e360>
2019-03-11 00:00:00,20190300,20190600,20190600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010f830>
2019-06-11 00:00:00,20190600,20190900,20190900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010e360>
2019-09-11 00:00:00,20190900,20191200,20191200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd70>
2019-12-11 00:00:00,20191200,20200300,20200300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fce0>
2020-03-11 00:00:00,20200300,20200600,20200600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010c590>
2020-06-11 00:00:00,20200600,20200900,20200900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010e360>
2020-09-11 00:00:00,20200900,20201200,20201200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd70>
2020-12-11 00:00:00,20201200,20210300,20210300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fce0>
2021-03-11 00:00:00,20210300,20210600,20210600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010ef90>
2021-06-11 00:00:00,20210600,20210900,20210900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010e360>
2021-09-11 00:00:00,20210900,20211200,20211200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010c590>
2021-12-11 00:00:00,20211200,20220300,20220300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fce0>
2022-03-11 00:00:00,20220300,20220600,20220600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd70>
2022-06-11 00:00:00,20220600,20220900,20220900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010e360>
2022-09-11 00:00:00,20220900,20221200,20221200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010ef90>
2022-12-11 00:00:00,20221200,20230300,20230300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fce0>
2023-03-11 00:00:00,20230300,20230600,20230600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010c590>
2023-06-11 00:00:00,20230600,20230900,20230900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010e360>
2023-09-11 00:00:00,20230900,20231200,20231200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd70>
2023-12-11 00:00:00,20231200,20240300,20240300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fce0>
2024-03-11 00:00:00,20240300,20240600,20240600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd10>
2024-06-11 00:00:00,20240600,20240900,20240900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010f830>
2024-09-11 00:00:00,20240900,20241200,20241200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010cdd0>
2024-12-11 00:00:00,20241200,20250300,20250300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010c590>
2025-03-11 00:00:00,20250300,20250600,20250600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010ef90>
2025-06-11 00:00:00,20250600,20250900,20250900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd70>
2025-09-11 00:00:00,20250900,20251200,20251200
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010c590>
2025-12-11 00:00:00,20251200,20260300,20260300
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd10>
2026-03-11 00:00:00,20260300,20260600,20260600
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fd70>
2026-06-11 00:00:00,20260600,20260900,20260900
<sysobjects.roll_parameters_with_price_data.contractWithRollParametersAndPrices object at 0x7fff6010fad0>
Changed date from 2015-06-11 00:00:00 to 2015-06-17 14:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2015-06-17 14:00:00')), ('current_contract', '20150600'), ('next_contract', '20150900'), ('carry_contract', '20150900')])
Changed date from 2015-09-11 00:00:00 to 2015-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2015-09-11 05:00:00')), ('current_contract', '20150900'), ('next_contract', '20151200'), ('carry_contract', '20151200')])
Changed date from 2015-12-11 00:00:00 to 2015-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2015-12-11 06:00:00')), ('current_contract', '20151200'), ('next_contract', '20160300'), ('carry_contract', '20160300')])
Changed date from 2016-03-11 00:00:00 to 2016-03-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2016-03-11 06:00:00')), ('current_contract', '20160300'), ('next_contract', '20160600'), ('carry_contract', '20160600')])
Changed date from 2016-06-11 00:00:00 to 2016-06-10 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2016-06-10 05:00:00')), ('current_contract', '20160600'), ('next_contract', '20160900'), ('carry_contract', '20160900')])
Changed date from 2016-09-11 00:00:00 to 2016-09-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2016-09-12 05:00:00')), ('current_contract', '20160900'), ('next_contract', '20161200'), ('carry_contract', '20161200')])
Changed date from 2016-12-11 00:00:00 to 2016-12-12 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2016-12-12 06:00:00')), ('current_contract', '20161200'), ('next_contract', '20170300'), ('carry_contract', '20170300')])
Changed date from 2017-03-11 00:00:00 to 2017-03-10 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2017-03-10 06:00:00')), ('current_contract', '20170300'), ('next_contract', '20170600'), ('carry_contract', '20170600')])
Changed date from 2017-06-11 00:00:00 to 2017-06-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2017-06-12 05:00:00')), ('current_contract', '20170600'), ('next_contract', '20170900'), ('carry_contract', '20170900')])
Changed date from 2017-09-11 00:00:00 to 2017-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2017-09-11 05:00:00')), ('current_contract', '20170900'), ('next_contract', '20171200'), ('carry_contract', '20171200')])
Changed date from 2017-12-11 00:00:00 to 2017-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2017-12-11 06:00:00')), ('current_contract', '20171200'), ('next_contract', '20180300'), ('carry_contract', '20180300')])
Changed date from 2018-03-11 00:00:00 to 2018-03-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-03-12 05:00:00')), ('current_contract', '20180300'), ('next_contract', '20180600'), ('carry_contract', '20180600')])
Changed date from 2018-06-11 00:00:00 to 2018-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-06-11 05:00:00')), ('current_contract', '20180600'), ('next_contract', '20180900'), ('carry_contract', '20180900')])
Changed date from 2018-09-11 00:00:00 to 2018-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-09-11 05:00:00')), ('current_contract', '20180900'), ('next_contract', '20181200'), ('carry_contract', '20181200')])
Changed date from 2018-12-11 00:00:00 to 2018-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-12-11 06:00:00')), ('current_contract', '20181200'), ('next_contract', '20190300'), ('carry_contract', '20190300')])
Changed date from 2019-03-11 00:00:00 to 2019-03-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-03-11 05:00:00')), ('current_contract', '20190300'), ('next_contract', '20190600'), ('carry_contract', '20190600')])
Changed date from 2019-06-11 00:00:00 to 2019-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-06-11 05:00:00')), ('current_contract', '20190600'), ('next_contract', '20190900'), ('carry_contract', '20190900')])
Changed date from 2019-09-11 00:00:00 to 2019-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-09-11 05:00:00')), ('current_contract', '20190900'), ('next_contract', '20191200'), ('carry_contract', '20191200')])
Changed date from 2019-12-11 00:00:00 to 2019-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-12-11 06:00:00')), ('current_contract', '20191200'), ('next_contract', '20200300'), ('carry_contract', '20200300')])
Changed date from 2020-03-11 00:00:00 to 2020-03-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2020-03-11 05:00:00')), ('current_contract', '20200300'), ('next_contract', '20200600'), ('carry_contract', '20200600')])
Changed date from 2020-06-11 00:00:00 to 2020-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2020-06-11 05:00:00')), ('current_contract', '20200600'), ('next_contract', '20200900'), ('carry_contract', '20200900')])
Changed date from 2020-09-11 00:00:00 to 2020-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2020-09-11 05:00:00')), ('current_contract', '20200900'), ('next_contract', '20201200'), ('carry_contract', '20201200')])
Changed date from 2020-12-11 00:00:00 to 2020-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2020-12-11 06:00:00')), ('current_contract', '20201200'), ('next_contract', '20210300'), ('carry_contract', '20210300')])
Changed date from 2021-03-11 00:00:00 to 2021-03-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2021-03-11 06:00:00')), ('current_contract', '20210300'), ('next_contract', '20210600'), ('carry_contract', '20210600')])
Changed date from 2021-06-11 00:00:00 to 2021-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2021-06-11 05:00:00')), ('current_contract', '20210600'), ('next_contract', '20210900'), ('carry_contract', '20210900')])
Changed date from 2021-09-11 00:00:00 to 2021-09-10 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2021-09-10 05:00:00')), ('current_contract', '20210900'), ('next_contract', '20211200'), ('carry_contract', '20211200')])
Changed date from 2021-12-11 00:00:00 to 2021-12-10 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2021-12-10 06:00:00')), ('current_contract', '20211200'), ('next_contract', '20220300'), ('carry_contract', '20220300')])
Changed date from 2022-03-11 00:00:00 to 2022-03-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2022-03-11 06:00:00')), ('current_contract', '20220300'), ('next_contract', '20220600'), ('carry_contract', '20220600')])
Changed date from 2022-06-11 00:00:00 to 2022-06-10 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2022-06-10 05:00:00')), ('current_contract', '20220600'), ('next_contract', '20220900'), ('carry_contract', '20220900')])
Changed date from 2022-09-11 00:00:00 to 2022-09-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2022-09-12 05:00:00')), ('current_contract', '20220900'), ('next_contract', '20221200'), ('carry_contract', '20221200')])
Changed date from 2022-12-11 00:00:00 to 2022-12-12 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2022-12-12 06:00:00')), ('current_contract', '20221200'), ('next_contract', '20230300'), ('carry_contract', '20230300')])
Changed date from 2023-03-11 00:00:00 to 2023-03-10 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2023-03-10 06:00:00')), ('current_contract', '20230300'), ('next_contract', '20230600'), ('carry_contract', '20230600')])
Changed date from 2023-06-11 00:00:00 to 2023-06-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2023-06-12 05:00:00')), ('current_contract', '20230600'), ('next_contract', '20230900'), ('carry_contract', '20230900')])
Changed date from 2023-09-11 00:00:00 to 2023-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2023-09-11 05:00:00')), ('current_contract', '20230900'), ('next_contract', '20231200'), ('carry_contract', '20231200')])
Changed date from 2023-12-11 00:00:00 to 2023-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2023-12-11 06:00:00')), ('current_contract', '20231200'), ('next_contract', '20240300'), ('carry_contract', '20240300')])
Changed date from 2024-03-11 00:00:00 to 2024-03-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2024-03-11 05:00:00')), ('current_contract', '20240300'), ('next_contract', '20240600'), ('carry_contract', '20240600')])
Changed date from 2024-06-11 00:00:00 to 2024-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2024-06-11 05:00:00')), ('current_contract', '20240600'), ('next_contract', '20240900'), ('carry_contract', '20240900')])
Changed date from 2024-09-11 00:00:00 to 2024-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2024-09-11 05:00:00')), ('current_contract', '20240900'), ('next_contract', '20241200'), ('carry_contract', '20241200')])
Changed date from 2024-12-11 00:00:00 to 2024-12-13 09:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2024-12-13 09:00:00')), ('current_contract', '20241200'), ('next_contract', '20250300'), ('carry_contract', '20250300')])
Changed date from 2025-03-11 00:00:00 to 2025-03-11 23:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2025-03-11 23:00:00')), ('current_contract', '20250300'), ('next_contract', '20250600'), ('carry_contract', '20250600')])
Changed date from 2025-06-11 00:00:00 to 2025-06-11 21:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2025-06-11 21:00:00')), ('current_contract', '20250600'), ('next_contract', '20250900'), ('carry_contract', '20250900')])
Changed date from 2025-09-11 00:00:00 to 2025-09-11 23:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2025-09-11 23:00:00')), ('current_contract', '20250900'), ('next_contract', '20251200'), ('carry_contract', '20251200')])
Changed date from 2025-12-11 00:00:00 to 2025-12-11 23:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2025-12-11 23:00:00')), ('current_contract', '20251200'), ('next_contract', '20260300'), ('carry_contract', '20260300')])
Changed date from 2026-03-11 00:00:00 to 2026-01-13 23:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2026-01-13 23:00:00')), ('current_contract', '20260300'), ('next_contract', '20260600'), ('carry_contract', '20260600')])
Need one of yes/no, Yes/No, y/n, Y/N
Need one of yes/no, Yes/No, y/n, Y/N
Adding roll calendar
2026-01-14 12:20:16 DEBUG csvRollCalendarData {'instrument_code': 'EU-REALESTATE'} Updating log attributes
2026-01-14 12:20:16 DEBUG csvRollCalendarData {'instrument_code': 'EU-REALESTATE'} Wrote calendar for EU-REALESTATE to /home/algotrader/pst/pysystemtrade-private/private/futures/roll_calendars_csv/EU-REALESTATE.csv
2026-01-14 12:20:16 DEBUG csvRollCalendarData {'instrument_code': 'EU-REALESTATE'} Added roll calendar for instrument EU-REALESTATE

                    current_contract next_contract carry_contract
current_roll_date
2015-06-17 14:00:00         20150600      20150900       20150900
2015-09-11 05:00:00         20150900      20151200       20151200
2015-12-11 06:00:00         20151200      20160300       20160300
2016-03-11 06:00:00         20160300      20160600       20160600
2016-06-10 05:00:00         20160600      20160900       20160900
2016-09-12 05:00:00         20160900      20161200       20161200
2016-12-12 06:00:00         20161200      20170300       20170300
2017-03-10 06:00:00         20170300      20170600       20170600
2017-06-12 05:00:00         20170600      20170900       20170900
2017-09-11 05:00:00         20170900      20171200       20171200
2017-12-11 06:00:00         20171200      20180300       20180300
2018-03-12 05:00:00         20180300      20180600       20180600
2018-06-11 05:00:00         20180600      20180900       20180900
2018-09-11 05:00:00         20180900      20181200       20181200
2018-12-11 06:00:00         20181200      20190300       20190300
2019-03-11 05:00:00         20190300      20190600       20190600
2019-06-11 05:00:00         20190600      20190900       20190900
2019-09-11 05:00:00         20190900      20191200       20191200
2019-12-11 06:00:00         20191200      20200300       20200300
2020-03-11 05:00:00         20200300      20200600       20200600
2020-06-11 05:00:00         20200600      20200900       20200900
2020-09-11 05:00:00         20200900      20201200       20201200
2020-12-11 06:00:00         20201200      20210300       20210300
2021-03-11 06:00:00         20210300      20210600       20210600
2021-06-11 05:00:00         20210600      20210900       20210900
2021-09-10 05:00:00         20210900      20211200       20211200
2021-12-10 06:00:00         20211200      20220300       20220300
2022-03-11 06:00:00         20220300      20220600       20220600
2022-06-10 05:00:00         20220600      20220900       20220900
2022-09-12 05:00:00         20220900      20221200       20221200
2022-12-12 06:00:00         20221200      20230300       20230300
2023-03-10 06:00:00         20230300      20230600       20230600
2023-06-12 05:00:00         20230600      20230900       20230900
2023-09-11 05:00:00         20230900      20231200       20231200
2023-12-11 06:00:00         20231200      20240300       20240300
2024-03-11 05:00:00         20240300      20240600       20240600
2024-06-11 05:00:00         20240600      20240900       20240900
2024-09-11 05:00:00         20240900      20241200       20241200
2024-12-13 09:00:00         20241200      20250300       20250300
2025-03-11 23:00:00         20250300      20250600       20250600
2025-06-11 21:00:00         20250600      20250900       20250900
2025-09-11 23:00:00         20250900      20251200       20251200
2025-12-11 23:00:00         20251200      20260300       20260300
2026-01-13 23:00:00         20260300      20260600       20260600

### Create multiple prices

This section will create multiple prices. Make sure you have a reliable calendar and you have set the instrument code in the above section.

In [5]:
process_multiple_prices_single_instrument(instrument_code=instrument_code)

Getting prices to adjust roll calendar
Changed date from 2015-06-17 14:00:00 to 2015-06-17 14:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2015-06-17 14:00:00')), ('current_contract', 20150600), ('next_contract', 20150900), ('carry_contract', 20150900)])
Changed date from 2015-09-11 05:00:00 to 2015-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2015-09-11 05:00:00')), ('current_contract', 20150900), ('next_contract', 20151200), ('carry_contract', 20151200)])
Changed date from 2015-12-11 06:00:00 to 2015-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2015-12-11 06:00:00')), ('current_contract', 20151200), ('next_contract', 20160300), ('carry_contract', 20160300)])
Changed date from 2016-03-11 06:00:00 to 2016-03-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2016-03-11 06:00:00')), ('current_contract', 20160300), ('next_contract', 20160600), ('carry_contract', 20160600)])
Changed date from 2016-06-10 05:00:00 to 2016-06-10 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2016-06-10 05:00:00')), ('current_contract', 20160600), ('next_contract', 20160900), ('carry_contract', 20160900)])
Changed date from 2016-09-12 05:00:00 to 2016-09-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2016-09-12 05:00:00')), ('current_contract', 20160900), ('next_contract', 20161200), ('carry_contract', 20161200)])
Changed date from 2016-12-12 06:00:00 to 2016-12-12 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2016-12-12 06:00:00')), ('current_contract', 20161200), ('next_contract', 20170300), ('carry_contract', 20170300)])
Changed date from 2017-03-10 06:00:00 to 2017-03-10 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2017-03-10 06:00:00')), ('current_contract', 20170300), ('next_contract', 20170600), ('carry_contract', 20170600)])
Changed date from 2017-06-12 05:00:00 to 2017-06-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2017-06-12 05:00:00')), ('current_contract', 20170600), ('next_contract', 20170900), ('carry_contract', 20170900)])
Changed date from 2017-09-11 05:00:00 to 2017-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2017-09-11 05:00:00')), ('current_contract', 20170900), ('next_contract', 20171200), ('carry_contract', 20171200)])
Changed date from 2017-12-11 06:00:00 to 2017-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2017-12-11 06:00:00')), ('current_contract', 20171200), ('next_contract', 20180300), ('carry_contract', 20180300)])
Changed date from 2018-03-12 05:00:00 to 2018-03-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-03-12 05:00:00')), ('current_contract', 20180300), ('next_contract', 20180600), ('carry_contract', 20180600)])
Changed date from 2018-06-11 05:00:00 to 2018-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-06-11 05:00:00')), ('current_contract', 20180600), ('next_contract', 20180900), ('carry_contract', 20180900)])
Changed date from 2018-09-11 05:00:00 to 2018-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-09-11 05:00:00')), ('current_contract', 20180900), ('next_contract', 20181200), ('carry_contract', 20181200)])
Changed date from 2018-12-11 06:00:00 to 2018-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2018-12-11 06:00:00')), ('current_contract', 20181200), ('next_contract', 20190300), ('carry_contract', 20190300)])
Changed date from 2019-03-11 05:00:00 to 2019-03-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-03-11 05:00:00')), ('current_contract', 20190300), ('next_contract', 20190600), ('carry_contract', 20190600)])
Changed date from 2019-06-11 05:00:00 to 2019-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-06-11 05:00:00')), ('current_contract', 20190600), ('next_contract', 20190900), ('carry_contract', 20190900)])
Changed date from 2019-09-11 05:00:00 to 2019-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-09-11 05:00:00')), ('current_contract', 20190900), ('next_contract', 20191200), ('carry_contract', 20191200)])
Changed date from 2019-12-11 06:00:00 to 2019-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2019-12-11 06:00:00')), ('current_contract', 20191200), ('next_contract', 20200300), ('carry_contract', 20200300)])
Changed date from 2020-03-11 05:00:00 to 2020-03-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2020-03-11 05:00:00')), ('current_contract', 20200300), ('next_contract', 20200600), ('carry_contract', 20200600)])
Changed date from 2020-06-11 05:00:00 to 2020-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2020-06-11 05:00:00')), ('current_contract', 20200600), ('next_contract', 20200900), ('carry_contract', 20200900)])
Changed date from 2020-09-11 05:00:00 to 2020-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2020-09-11 05:00:00')), ('current_contract', 20200900), ('next_contract', 20201200), ('carry_contract', 20201200)])
Changed date from 2020-12-11 06:00:00 to 2020-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2020-12-11 06:00:00')), ('current_contract', 20201200), ('next_contract', 20210300), ('carry_contract', 20210300)])
Changed date from 2021-03-11 06:00:00 to 2021-03-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2021-03-11 06:00:00')), ('current_contract', 20210300), ('next_contract', 20210600), ('carry_contract', 20210600)])
Changed date from 2021-06-11 05:00:00 to 2021-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2021-06-11 05:00:00')), ('current_contract', 20210600), ('next_contract', 20210900), ('carry_contract', 20210900)])
Changed date from 2021-09-10 05:00:00 to 2021-09-10 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2021-09-10 05:00:00')), ('current_contract', 20210900), ('next_contract', 20211200), ('carry_contract', 20211200)])
Changed date from 2021-12-10 06:00:00 to 2021-12-10 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2021-12-10 06:00:00')), ('current_contract', 20211200), ('next_contract', 20220300), ('carry_contract', 20220300)])
Changed date from 2022-03-11 06:00:00 to 2022-03-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2022-03-11 06:00:00')), ('current_contract', 20220300), ('next_contract', 20220600), ('carry_contract', 20220600)])
Changed date from 2022-06-10 05:00:00 to 2022-06-10 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2022-06-10 05:00:00')), ('current_contract', 20220600), ('next_contract', 20220900), ('carry_contract', 20220900)])
Changed date from 2022-09-12 05:00:00 to 2022-09-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2022-09-12 05:00:00')), ('current_contract', 20220900), ('next_contract', 20221200), ('carry_contract', 20221200)])
Changed date from 2022-12-12 06:00:00 to 2022-12-12 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2022-12-12 06:00:00')), ('current_contract', 20221200), ('next_contract', 20230300), ('carry_contract', 20230300)])
Changed date from 2023-03-10 06:00:00 to 2023-03-10 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2023-03-10 06:00:00')), ('current_contract', 20230300), ('next_contract', 20230600), ('carry_contract', 20230600)])
Changed date from 2023-06-12 05:00:00 to 2023-06-12 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2023-06-12 05:00:00')), ('current_contract', 20230600), ('next_contract', 20230900), ('carry_contract', 20230900)])
Changed date from 2023-09-11 05:00:00 to 2023-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2023-09-11 05:00:00')), ('current_contract', 20230900), ('next_contract', 20231200), ('carry_contract', 20231200)])
Changed date from 2023-12-11 06:00:00 to 2023-12-11 06:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2023-12-11 06:00:00')), ('current_contract', 20231200), ('next_contract', 20240300), ('carry_contract', 20240300)])
Changed date from 2024-03-11 05:00:00 to 2024-03-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2024-03-11 05:00:00')), ('current_contract', 20240300), ('next_contract', 20240600), ('carry_contract', 20240600)])
Changed date from 2024-06-11 05:00:00 to 2024-06-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2024-06-11 05:00:00')), ('current_contract', 20240600), ('next_contract', 20240900), ('carry_contract', 20240900)])
Changed date from 2024-09-11 05:00:00 to 2024-09-11 05:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2024-09-11 05:00:00')), ('current_contract', 20240900), ('next_contract', 20241200), ('carry_contract', 20241200)])
Changed date from 2024-12-13 09:00:00 to 2024-12-13 09:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2024-12-13 09:00:00')), ('current_contract', 20241200), ('next_contract', 20250300), ('carry_contract', 20250300)])
Changed date from 2025-03-11 23:00:00 to 2025-03-11 23:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2025-03-11 23:00:00')), ('current_contract', 20250300), ('next_contract', 20250600), ('carry_contract', 20250600)])
Changed date from 2025-06-11 21:00:00 to 2025-06-11 21:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2025-06-11 21:00:00')), ('current_contract', 20250600), ('next_contract', 20250900), ('carry_contract', 20250900)])
Changed date from 2025-09-11 23:00:00 to 2025-09-11 23:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2025-09-11 23:00:00')), ('current_contract', 20250900), ('next_contract', 20251200), ('carry_contract', 20251200)])
Changed date from 2025-12-11 23:00:00 to 2025-12-11 23:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2025-12-11 23:00:00')), ('current_contract', 20251200), ('next_contract', 20260300), ('carry_contract', 20260300)])
Changed date from 2026-01-13 23:00:00 to 2026-01-13 23:00:00 for row with contracts dict_items([('current_roll_date', Timestamp('2026-01-13 23:00:00')), ('current_contract', 20260300), ('next_contract', 20260600), ('carry_contract', 20260600)])
                     PRICE  FORWARD  CARRY PRICE_CONTRACT FORWARD_CONTRACT  \
index
2015-06-18 05:00:00  175.3    174.5  174.5       20150900         20151200
2015-06-18 08:00:00  174.7      NaN    NaN       20150900         20151200
2015-06-19 05:00:00  175.6    174.8  174.8       20150900         20151200
2015-06-19 09:00:00  176.9      NaN    NaN       20150900         20151200
2015-06-19 10:00:00  176.9      NaN    NaN       20150900         20151200
...                    ...      ...    ...            ...              ...
2026-01-13 19:00:00  129.1      NaN    NaN       20260300         20260600
2026-01-13 20:00:00  129.1      NaN    NaN       20260300         20260600
2026-01-13 21:00:00  129.1      NaN    NaN       20260300         20260600
2026-01-13 22:00:00  129.1      NaN    NaN       20260300         20260600
2026-01-13 23:00:00  128.6    125.9  125.9       20260300         20260600

                    CARRY_CONTRACT
index
2015-06-18 05:00:00       20151200
2015-06-18 08:00:00       20151200
2015-06-19 05:00:00       20151200
2015-06-19 09:00:00       20151200
2015-06-19 10:00:00       20151200
...                            ...
2026-01-13 19:00:00       20260600
2026-01-13 20:00:00       20260600
2026-01-13 21:00:00       20260600
2026-01-13 22:00:00       20260600
2026-01-13 23:00:00       20260600

[19646 rows x 6 columns]
2026-01-14 12:21:03 DEBUG root {'component': 'parquetFuturesMultiplePricesData', 'instrument_code': 'EU-REALESTATE'} Wrote 19646 lines of prices for EU-REALESTATE to parquetFuturesMultiplePricesData
2026-01-14 12:21:03 INFO root {'component': 'parquetFuturesMultiplePricesData', 'instrument_code': 'EU-REALESTATE'} Added data for instrument EU-REALESTATE

,PRICE,FORWARD,CARRY,PRICE_CONTRACT,FORWARD_CONTRACT,CARRY_CONTRACT
index,,,,,,
2015-06-18 05:00:00,175.3,174.5,174.5,20150900,20151200,20151200
2015-06-18 08:00:00,174.7,NaN,NaN,20150900,20151200,20151200
2015-06-19 05:00:00,175.6,174.8,174.8,20150900,20151200,20151200
2015-06-19 09:00:00,176.9,NaN,NaN,20150900,20151200,20151200
2015-06-19 10:00:00,176.9,NaN,NaN,20150900,20151200,20151200
...,...,...,...,...,...,...
2026-01-13 19:00:00,129.1,NaN,NaN,20260300,20260600,20260600
2026-01-13 20:00:00,129.1,NaN,NaN,20260300,20260600,20260600
2026-01-13 21:00:00,129.1,NaN,NaN,20260300,20260600,20260600
2026-01-13 22:00:00,129.1,NaN,NaN,20260300,20260600,20260600
2026-01-13 23:00:00,128.6,125.9,125.9,20260300,20260600,20260600

### Create adjusted prices

This will create adjusted prices from the multiple ones.

In [6]:
process_adjusted_prices_single_instrument(instrument_code=instrument_code)

index
2015-06-18 05:00:00    131.4
2015-06-18 08:00:00    130.8
2015-06-19 05:00:00    131.7
2015-06-19 09:00:00    133.0
2015-06-19 10:00:00    133.0
                       ...
2026-01-13 19:00:00    129.1
2026-01-13 20:00:00    129.1
2026-01-13 21:00:00    129.1
2026-01-13 22:00:00    129.1
2026-01-13 23:00:00    128.6
Length: 19646, dtype: float64
2026-01-14 12:21:18 DEBUG root {'component': 'parquetFuturesAdjustedPricesData', 'instrument_code': 'EU-REALESTATE'} Wrote 19646 lines of prices for EU-REALESTATE to parquetFuturesAdjustedPrices
2026-01-14 12:21:18 INFO root {'component': 'parquetFuturesAdjustedPricesData', 'instrument_code': 'EU-REALESTATE'} Added data for instrument EU-REALESTATE

index
2015-06-18 05:00:00    131.4
2015-06-18 08:00:00    130.8
2015-06-19 05:00:00    131.7
2015-06-19 09:00:00    133.0
2015-06-19 10:00:00    133.0
                       ...
2026-01-13 19:00:00    129.1
2026-01-13 20:00:00    129.1
2026-01-13 21:00:00    129.1
2026-01-13 22:00:00    129.1
2026-01-13 23:00:00    128.6
Length: 19646, dtype: float64